# Copyright 2025 MicroEJ Corp. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be found with this software.

# These variables are used to centralize versioned dependencies. It is used by the individual build.gradle.kts files.

[versions]
microej-sdk = "1.1.0"

[libraries]
# APIs
api-edc =                       { group = "ej.api", name = "edc", version = "1.3.7" }
api-bon =                       { group = "ej.api", name = "bon", version = "1.4.4" }

# Add-on libraries
library-logging =               { group = "ej.library.eclasspath", name = "logging", version = "1.2.1" }
library-formatter =             { group = "ej.library.eclasspath", name = "formatter", version = "2.3.0" }

# Default VEE Port
vee-port-nxp-mimxrt1170 =       { group = "com.nxp.vee.mimxrt1170", name = "vee-port", version = "3.0.0" }